output_style = "verbose"    # compact | verbose
color_scheme = "monokai-github-meta"
#color_scheme = "dracula"
no_color = false

[fields]
timestamp = "timestamp"
level = "level"
message_fields = ["message"]
main_line_fields = ["timestamp", "level", "logger", "message"]
