output_style = "verbose"    # compact | verbose
color_scheme = "monokai-github-meta"
#color_scheme = "dracula"
no_color = false

[fields]
timestamp = "timestamp"
level = "level"
file = "file"
function = "function"
line = "line"
message_fields = ["message"]
main_line_fields = ["timestamp", "level", "file", "origin", "message"]
